server:
  port: 80

#配置用户名密码
#spring:
#  security:
#    user:
#      name: java2102
#      password: 123456
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitydb?useSSL=false&serverTimezone=GMT&characterEncoding=UTF8&useUnicode=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  type-aliases-package: com.qf.java2102.springsecurity.demo01.pojo
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    com.qf.java2102.springsecurity.demo01: debug
